# Generated by Django 5.2.3 on 2025-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepictures/profilepic.jpg', upload_to='profilepictures'),
        ),
    ]
